# Generated by Django 4.1.5 on 2023-06-14 11:24

import autoslug.fields
import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=300, null=True)),
                ('blog_img', models.ImageField(blank=True, upload_to='media')),
                ('blog_desp', ckeditor.fields.RichTextField()),
                ('blog_date', models.DateField()),
                ('blog_author', models.CharField(max_length=30, null=True)),
                ('blog_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='blog_title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_img', models.ImageField(upload_to='media')),
                ('course_bann', models.ImageField(null=True, upload_to='media')),
                ('course_price', models.CharField(max_length=6, null=True)),
                ('course_title', models.CharField(max_length=50, null=True)),
                ('course_descp', ckeditor.fields.RichTextField()),
                ('course_stu', models.CharField(max_length=5, null=True)),
                ('course_lessons', models.CharField(max_length=4, null=True)),
                ('course_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='course_title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='email_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_title', models.CharField(max_length=200, null=True)),
                ('event_img', models.ImageField(upload_to='media')),
                ('event_descp', ckeditor.fields.RichTextField()),
                ('event_date', models.DateField()),
                ('event_time', models.TimeField()),
                ('event_location', models.CharField(max_length=30, null=True)),
                ('event_slug', autoslug.fields.AutoSlugField(default=None, editable=False, null=True, populate_from='event_title', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='news',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='q_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
                ('subject', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='query_form',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_name', models.CharField(max_length=100, null=True)),
                ('form_email', models.CharField(max_length=100, null=True)),
                ('form_subject', models.CharField(max_length=100, null=True)),
                ('form_message', models.CharField(max_length=1000, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slider_name', models.CharField(max_length=50, null=True)),
                ('slider_img', models.ImageField(null=True, upload_to='static/slider')),
                ('Details', ckeditor.fields.RichTextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='StuReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stu_name', models.CharField(max_length=40, null=True)),
                ('stu_descp', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
