# Generated by Django 4.1.5 on 2023-06-15 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='join_with_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, null=True)),
                ('phone', models.CharField(max_length=15, null=True)),
                ('message', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
