# Generated by Django 4.1.5 on 2023-06-15 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0002_join_with_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='q_form',
            name='subject',
        ),
    ]
