# Generated by Django 4.1.5 on 2023-06-23 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aviation', '0003_remove_q_form_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
