# Generated by Django 4.1.5 on 2023-06-14 11:24

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Admin', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Student_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(max_length=35, null=True)),
                ('Number', models.CharField(max_length=10, null=True)),
                ('DOB', models.DateField(null=True)),
                ('Aadhaar', models.CharField(max_length=12, null=True)),
                ('Enrollment_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('Admission_no', models.CharField(default='TITAN/365722', max_length=10)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], max_length=6, null=True)),
                ('Education', models.CharField(choices=[('10th', 'Secondary education'), ('12th', 'Senior secondary education'), ('Grad', 'Graduation education'), ('P.Grad', 'Post Graduation education')], max_length=50, null=True)),
                ('doc_10th', models.FileField(blank=True, null=True, upload_to='static/docs/')),
                ('doc_12th', models.FileField(blank=True, null=True, upload_to='static/docs/')),
                ('doc_Graduate', models.FileField(blank=True, null=True, upload_to='static/docs/')),
                ('doc_postgraduate', models.FileField(blank=True, null=True, upload_to='static/docs/')),
                ('Address', models.TextField(max_length=200, null=True)),
                ('State', models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Assam', 'Assam'), ('Bihar', 'Bihar'), ('Chhattisgarh', 'Chhattisgarh'), ('Goa', 'Goa'), ('Gujarat', 'Gujarat'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Jharkhand', 'Jharkhand'), ('Karnataka', 'Karnataka'), ('Kerala', 'Kerala'), ('Madhya Pradesh', 'Madhya Pradesh'), ('Maharashtra', 'Maharashtra'), ('Manipur', 'Manipur'), ('Meghalaya', 'Meghalaya'), ('Mizoram', 'Mizoram'), ('Nagaland', 'Nagaland'), ('Odisha', 'Odisha'), ('Punjab', 'Punjab'), ('Rajasthan', 'Rajasthan'), ('Sikkim', 'Sikkim'), ('Tamil Nadu', 'Tamil Nadu'), ('Telangana', 'Telangana'), ('Tripura', 'Tripura'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Andaman and Nicobar Islands', 'Andaman and Nicobar Islands'), ('Chandigarh', 'Chandigarh'), ('Dadra & Nagar Haveli and Daman & Diu', 'Dadra & Nagar Haveli and Daman & Diu'), ('Delhi', 'Delhi'), ('Jammu and Kashmir', 'Jammu and Kashmir'), ('Lakshadweep', 'Lakshadweep'), ('Puducherry', 'Puducherry'), ('Ladakh', 'Ladakh')], max_length=60, null=True)),
                ('City', models.CharField(max_length=20, null=True)),
                ('House', models.CharField(max_length=15, null=True)),
                ('Post_office', models.CharField(max_length=15, null=True)),
                ('Tehsil', models.CharField(max_length=15, null=True)),
                ('District', models.CharField(max_length=20, null=True)),
                ('Pincode', models.CharField(max_length=6, null=True)),
                ('date_of_joining', models.DateField(default=datetime.datetime.today)),
                ('paid_amount', models.BigIntegerField(default=0)),
                ('Payment', models.BooleanField(default='False')),
                ('Trm', models.BooleanField(default='False')),
                ('Course_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Admin.course')),
            ],
        ),
        migrations.CreateModel(
            name='Student_Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('email', models.CharField(max_length=20, null=True)),
                ('payment_id', models.CharField(max_length=150, null=True)),
                ('Razorpay_Order_Id', models.CharField(max_length=200, null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('Admission_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student_detail')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, verbose_name='Customer Name')),
                ('date', models.DateField(default=datetime.date.today)),
                ('date2', models.DateTimeField(default=datetime.datetime.now)),
                ('amount', models.FloatField(verbose_name='Amount')),
                ('status', models.CharField(default='Pending', max_length=254, verbose_name='Payment Status')),
                ('provider_order_id', models.CharField(max_length=40, verbose_name='Order ID')),
                ('payment_id', models.CharField(max_length=36, verbose_name='Payment ID')),
                ('signature_id', models.CharField(max_length=128, verbose_name='Signature ID')),
                ('Admission_no', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Student.student_detail')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
